#!/bin/bash

set -eu

build_dir="`pwd`/build"
code_sign_identity="Developer ID Application: Hive Labs Ltd (VK4N5L9C69)"
which xctool && xc=xctool || xc=xcodebuild

function print_summary() {
    local highlight=`tput setaf 3`
    local reset=`tput sgr0`

    echo "Build:              ${highlight}Release${reset}"
    echo "Code sign identity: ${highlight}$code_sign_identity${reset}"
    echo "Target:             ${highlight}build/Hive.app.zip${reset}"
}

print_summary
echo

LC_ALL="en_US.UTF-8" pod install

$xc \
    CODE_SIGN_IDENTITY="$code_sign_identity" \
    BUILD_DIR="$build_dir" \
    BUILD_ROOT="$build_dir" \
    CONFIGURATION_BUILD_DIR="$build_dir" \
    OBJROOT="$build_dir/Intermediates" \
    SYMROOT="$build_dir/Intermediates" \
    MODULE_CACHE_DIR="$build_dir/ModuleCache" \
    SHARED_PRECOMPS_DIR="$build_dir/PrecompiledHeaders" \
    -workspace Hive.xcworkspace \
    -scheme Hive \
    -configuration Release \
    build

(cd build
    rm -f Hive.app.zip
    zip -qry Hive.app.zip Hive.app
) || exit $?

print_summary
